### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/PointGreyCamera#1]
- [ ] Start-stop via GPIO using TTL. Arduino sends the TTL pulse. 600 ms before CS and ending 200 ms post US (2 to 3sec total for a trail ).
- [ ] User defined ROI 
- [ ] Easy identification of Data files.

**Comment by dilawar** [comment]
Camera server is working great. We are not tweaking it anymore.
